baseURL = "http://dakotanelson.com/"
languageCode = "en-us"
title = "Dakota Nelson"
theme = "book"

enableGitInfo = true

[params]
    # how many levels of ToC?
    BookToC = 2
    BookMenuBundle = '/menu'
    BookSection = 'docs'
    BookRepo = 'https://github.com/dakotanelson/dakotanelson.github.io'
    firstName = "Dakota"
    lastName = "Nelson"
    address = "Seattle, WA"
#phone = "1-555-555-1234"
    contactNote = ""
    profileImage = "img/me_alt.jpg"
    email = "dakota.w.nelson@gmail.com"
    description = "Dakota is a pentester and security researcher in Seattle, WA."
    favicon = "img/favicon.ico"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dakotanelson/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/dakotanelson/"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/dakota"
    icon = "keybase"

[params.google.analytics]
    trackerID = "UA-50003361-1"
