---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Projects
- type: document
  path: content/projects/creations
  label: Created Projects
- type: directory
  path: content/projects/contributions
  label: Contributed Projects
  create: documents
  match: "**/*"
- type: directory
  path: content/publications
  label: Publications
  create: all
  match: "**/*"
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: Welcome Section
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.37.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.37.1
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
version: 0.37.1
